# Generated by Django 4.1.7 on 2023-03-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payplan",
            old_name="updateed_at",
            new_name="updated_at",
        ),
    ]
