# Generated by Django 4.1.7 on 2023-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_users_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="사용자 이름", max_length=128)),
                ("content", models.TextField(help_text="사용자 설명", max_length=1024)),
            ],
        ),
    ]
